spring.application.name=OnnetPC

# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/onnetpc
spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info

#Security
spring.security.user.name=admin
spring.security.user.password=admin
